version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_password # <<< RẤT QUAN TRỌNG: THAY BẰNG MẬT KHẨU MẠNH CỦA BẠN
      MYSQL_DATABASE: busstationmanagement
    # ports:
      # - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    # Đây là khối environment duy nhất và đúng
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: your_strong_password # <<< SỬ DỤNG CÙNG MẬT KHẨU VỚI MYSQL_ROOT_PASSWORD
      DB_NAME: busstationmanagement
      DISPLAY: host.docker.internal:0.0 # Cấu hình DISPLAY cho Windows
    depends_on:
      db:
        condition: service_healthy
    # Bạn không cần phần volumes này nữa, vì nó không cần thiết cho Tkinter trên Windows khi dùng host.docker.internal
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix # Xóa hoặc comment dòng này đi
    # privileged: true # Tránh sử dụng trừ khi thực sự cần và hiểu rủi ro

volumes:
  mysql_data: