version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123zzz 
      MYSQL_DATABASE: busstationmanagement
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123zzz 
      DB_NAME: busstationmanagement
      DISPLAY: host.docker.internal:0.0 
    depends_on:
      db:
        condition: service_healthy
   
volumes:
  mysql_data: